// packages/react/src/index.tsx
'use client'

import * as React from 'react'
import {
	type Value,
	type Format,
	SlottedTag,
	slottedStyles,
	partitionParts,
	type PartitionedParts,
	NumberFlowLite,
	prefersReducedMotion,
	canAnimate as _canAnimate
} from 'number-flow'
export type { Value, Format, Trend } from 'number-flow'

const isReact19 = React.version.startsWith('19.')

// Can't wait to not have to do this in React 19:
const OBSERVED_ATTRIBUTES = ['parts'] as const
type ObservedAttribute = (typeof OBSERVED_ATTRIBUTES)[number]
export class NumberFlowElement extends NumberFlowLite {
	static observedAttributes = OBSERVED_ATTRIBUTES
	attributeChangedCallback(attr: ObservedAttribute, _oldValue: string, newValue: string) {
		this[attr] = JSON.parse(newValue)
	}
}

NumberFlowElement.define()

export type NumberFlowProps = React.HTMLAttributes<NumberFlowElement> & {
	value: Value
	locales?: Intl.LocalesArgument
	format?: Format
	isolate?: boolean
	animated?: boolean
	respectMotionPreference?: boolean
	willChange?: boolean
	// animateDependencies?: React.DependencyList
	onAnimationsStart?: () => void
	onAnimationsFinish?: () => void
	trend?: (typeof NumberFlowElement)['prototype']['trend']
	opacityTiming?: (typeof NumberFlowElement)['prototype']['opacityTiming']
	transformTiming?: (typeof NumberFlowElement)['prototype']['transformTiming']
	spinTiming?: (typeof NumberFlowElement)['prototype']['spinTiming']
}

type NumberFlowImplProps = Omit<NumberFlowProps, 'value' | 'locales' | 'format'> & {
	innerRef: React.MutableRefObject<NumberFlowElement | undefined>
	parts: PartitionedParts
}

// You're supposed to cache these between uses:
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
// Serialize to strings b/c React:
const formatters: Record<string, Intl.NumberFormat> = {}

// Tiny workaround to support React 19 until it's released:
const serializeParts = isReact19 ? (p: PartitionedParts) => p : JSON.stringify

type NumberFlowImplState = {}
type NumberFlowImplSnapshot = boolean
// We need a class component to use getSnapshotBeforeUpdate:
class NumberFlowImpl extends React.Component<
	NumberFlowImplProps,
	NumberFlowImplState,
	NumberFlowImplSnapshot
> {
	constructor(props: NumberFlowImplProps) {
		super(props)
		this.handleRef = this.handleRef.bind(this)
	}

	// Update the non-parts props to avoid JSON serialization
	// Parts needs to be set in render still:
	updateNonPartsProps(prevProps?: Readonly<NumberFlowImplProps>) {
		if (!this.#el) return

		this.#el.manual = !this.props.isolate
		if (this.props.animated != null) this.#el.animated = this.props.animated
		if (this.props.respectMotionPreference != null)
			this.#el.respectMotionPreference = this.props.respectMotionPreference
		if (this.props.trend != null) this.#el.trend = this.props.trend
		if (this.props.opacityTiming) this.#el.opacityTiming = this.props.opacityTiming
		if (this.props.transformTiming) this.#el.transformTiming = this.props.transformTiming
		if (this.props.spinTiming) this.#el.spinTiming = this.props.spinTiming

		if (prevProps?.onAnimationsStart)
			this.#el.removeEventListener('animationsstart', prevProps.onAnimationsStart)
		if (this.props.onAnimationsStart)
			this.#el.addEventListener('animationsstart', this.props.onAnimationsStart)

		if (prevProps?.onAnimationsFinish)
			this.#el.removeEventListener('animationsfinish', prevProps.onAnimationsFinish)
		if (this.props.onAnimationsFinish)
			this.#el.addEventListener('animationsfinish', this.props.onAnimationsFinish)
	}

	override componentDidMount() {
		if (isReact19 && this.#el) {
			// React 19 doesn't seem to hydrate custom elements the same way, and these need to be set before being updated:
			this.#el.parts = this.props.parts
		}
		this.updateNonPartsProps()
	}

	override getSnapshotBeforeUpdate(prevProps: Readonly<NumberFlowImplProps>) {
		this.updateNonPartsProps(prevProps)
		if (this.props.isolate) return false
		if (prevProps.parts === this.props.parts) return false
		this.#el?.willUpdate()
		return true
	}

	override componentDidUpdate(
		_: Readonly<NumberFlowImplProps>,
		__: NumberFlowImplState,
		snapshot: NumberFlowImplSnapshot
	) {
		if (snapshot) this.#el?.didUpdate()
	}

	#el?: NumberFlowElement

	handleRef(el: NumberFlowElement) {
		if (this.props.innerRef) this.props.innerRef.current = el
		this.#el = el
	}

	override render() {
		const {
			innerRef,
			className,
			parts,
			willChange,
			// These are set in updateNonPartsProps, so ignore them here:
			animated,
			respectMotionPreference,
			isolate,
			trend,
			opacityTiming,
			transformTiming,
			spinTiming,
			...rest
		} = this.props

		return (
			// @ts-expect-error missing types
			<number-flow
				ref={this.handleRef}
				data-will-change={willChange ? '' : undefined}
				// Have to rename this:
				class={className}
				{...rest}
				// Make sure parts are set last, everything else is updated:
				parts={serializeParts(parts)}
			>
				<SlottedTag style={slottedStyles({ willChange })}>{parts.formatted}</SlottedTag>
				{/* @ts-expect-error missing types */}
			</number-flow>
		)
	}
}

const NumberFlow = React.forwardRef<NumberFlowElement, NumberFlowProps>(function NumberFlow(
	{ value, locales, format, ...props },
	_ref
) {
	React.useImperativeHandle(_ref, () => ref.current!, [])
	const ref = React.useRef<NumberFlowElement>()

	const localesString = React.useMemo(() => (locales ? JSON.stringify(locales) : ''), [locales])
	const formatString = React.useMemo(() => (format ? JSON.stringify(format) : ''), [format])
	const parts = React.useMemo(() => {
		const formatter = (formatters[`${localesString}:${formatString}`] ??= new Intl.NumberFormat(
			locales,
			format
		))
		return partitionParts(value, formatter)
	}, [value, localesString, formatString])

	return <NumberFlowImpl {...props} parts={parts} innerRef={ref} />
})

export default NumberFlow

// SSR-safe canAnimate
export function useCanAnimate({ respectMotionPreference = true } = {}) {
	const [canAnimate, setCanAnimate] = React.useState(_canAnimate)
	const [reducedMotion, setReducedMotion] = React.useState(false)

	// Handle SSR:
	React.useEffect(() => {
		setCanAnimate(_canAnimate)
		setReducedMotion(prefersReducedMotion?.matches ?? false)
	}, [])

	// Listen for reduced motion changes if needed:
	React.useEffect(() => {
		if (!respectMotionPreference) return
		const onChange = ({ matches }: MediaQueryListEvent) => {
			setReducedMotion(matches)
		}
		prefersReducedMotion?.addEventListener('change', onChange)
		return () => {
			prefersReducedMotion?.removeEventListener('change', onChange)
		}
	}, [respectMotionPreference])

	return canAnimate && (!respectMotionPreference || !reducedMotion)
}

// packages/vue/src/index.vue
<script lang="ts" setup>
import {
	type Value,
	type Format,
	render,
	partitionParts,
	NumberFlowLite,
	type Props as NumberFlowProps
} from 'number-flow'
import { computed, ref } from 'vue'

type Props = Partial<NumberFlowProps> & {
	locales?: Intl.LocalesArgument
	format?: Format
	value: Value
	willChange?: boolean
}

// This is repetitive but I couldn't get it any cleaner using `withDefaults`,
// because then you can't destructure,
// and if you don't set defaults Vue will use its own for i.e. booleans.
const {
	locales,
	format,
	value,
	trend = NumberFlowLite.defaultProps.trend,
	continuous = NumberFlowLite.defaultProps.continuous,
	animated = NumberFlowLite.defaultProps.animated,
	transformTiming = NumberFlowLite.defaultProps.transformTiming,
	spinTiming = NumberFlowLite.defaultProps.spinTiming,
	opacityTiming = NumberFlowLite.defaultProps.opacityTiming,
	respectMotionPreference = NumberFlowLite.defaultProps.respectMotionPreference,
	willChange = false
} = defineProps<Props>()

const el = ref<NumberFlowLite>()

defineExpose({ el })

defineOptions({
	inheritAttrs: false // set them manually to ensure `parts` updates last
})

// Technically the original animationsstart still emits but ah well:
const emit = defineEmits<{
	(e: 'animationsstart'): void
	(e: 'animationsfinish'): void
}>()

// You're supposed to cache these between uses:
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
const formatter = computed(() => new Intl.NumberFormat(locales, format))

const parts = computed(() => partitionParts(value, formatter.value))

// Pre effects don't seem to batch to handle grouping like React:
// https://discord.com/channels/325477692906536972/1299071468533055541
//
// watch(
// 	[parts, () => isolate],
// 	([_, isolate]) => {
// 		if (!isolate) el.value?.willUpdate()
// 	},
// 	{ flush: 'pre' }
// )
// watch(
// 	[parts, () => isolate],
// 	([_, isolate]) => {
// 		if (!isolate) el.value?.didUpdate()
// 	},
// 	{ flush: 'post' }
// )
</script>
<template>
	<!-- Make sure parts is set last: -->
	<number-flow-vue
		ref="el"
		v-bind="$attrs"
		:trend
		:continuous
		:animated
		:transformTiming
		:spinTiming
		:opacityTiming
		:respectMotionPreference
		:data-will-change="willChange ? '' : undefined"
		v-html="render({ formatted: parts.formatted, willChange })"
		@animationsstart="emit('animationsstart')"
		@animationsfinish="emit('animationsfinish')"
		:parts
	/>
</template>
